import re

from utils.response_builder import create_engine_response

from utils.constants import (
    ENGINE_AI_CONTENT_ANALYZER,
    STATUS_SUCCESS,
    STATUS_FAILED,
    RISK_LOW,
    RISK_MEDIUM,
    RISK_HIGH
)


def analyze_ai_content(job_data):
    """
    Analyzes the writing characteristics of a job posting
    for suspicious or low-information content patterns.

    This module does NOT determine whether text was definitely
    generated by AI. It identifies content characteristics that
    may contribute to a broader job-trust assessment.

    Parameters:
        job_data (dict): Job posting data

    Returns:
        dict: Standard engine response
    """

    result = create_engine_response(
        ENGINE_AI_CONTENT_ANALYZER
    )

    try:

        # =================================================
        # INPUT VALIDATION
        # =================================================

        if not isinstance(job_data, dict):

            result["status"] = STATUS_FAILED
            result["risk"] = RISK_HIGH

            result["errors"].append(
                "Job data must be provided as a dictionary."
            )

            return result

        job_description = str(
            job_data.get(
                "job_description",
                ""
            )
        ).strip()

        if not job_description:

            result["status"] = STATUS_FAILED
            result["risk"] = RISK_HIGH

            result["errors"].append(
                "Job description cannot be empty."
            )

            return result

        text = job_description.lower()

        # =================================================
        # INITIALIZATION
        # =================================================

        detected_characteristics = []

        # =================================================
        # CHECK 1 - GENERIC PROMOTIONAL LANGUAGE
        # =================================================

        promotional_phrases = [
            "great opportunity",
            "dream job",
            "exciting opportunity",
            "excellent opportunity",
            "amazing opportunity",
            "become part of our team",
            "unlock your potential",
            "change your life"
        ]

        promotional_matches = [
            phrase
            for phrase in promotional_phrases
            if phrase in text
        ]

        if promotional_matches:

            detected_characteristics.append(
                "Excessive promotional language"
            )

        # =================================================
        # CHECK 2 - VAGUE JOB DESCRIPTION
        # =================================================

        vague_phrases = [
            "simple work",
            "easy work",
            "work from home",
            "flexible work",
            "earn from home",
            "online work"
        ]

        vague_matches = [
            phrase
            for phrase in vague_phrases
            if phrase in text
        ]

        # Determine whether concrete responsibilities exist
        responsibility_terms = [
            "responsibilities",
            "requirements",
            "skills",
            "experience",
            "qualification",
            "duties",
            "role",
            "responsible for"
        ]

        responsibility_count = sum(
            1
            for term in responsibility_terms
            if term in text
        )

        if (
            vague_matches
            and responsibility_count == 0
        ):

            detected_characteristics.append(
                "Vague job description with limited role details"
            )

        # =================================================
        # CHECK 3 - REPETITIVE LANGUAGE
        # =================================================

        words = re.findall(
            r"\b[a-zA-Z]{4,}\b",
            text
        )

        word_frequency = {}

        for word in words:

            word_frequency[word] = (
                word_frequency.get(
                    word,
                    0
                ) + 1
            )

        repeated_words = [
            word
            for word, count in word_frequency.items()
            if count >= 5
        ]

        if len(repeated_words) >= 2:

            detected_characteristics.append(
                "Repeated promotional or descriptive language"
            )

        # =================================================
        # CHECK 4 - EXCESSIVE EXCLAMATION
        # =================================================

        exclamation_count = text.count("!")

        if exclamation_count >= 3:

            detected_characteristics.append(
                "Excessive exclamation usage"
            )

        # =================================================
        # CHECK 5 - GENERIC CALL TO ACTION
        # =================================================

        call_to_action_phrases = [
            "apply now",
            "join now",
            "contact us today",
            "don't miss this opportunity",
            "hurry up",
            "limited vacancies",
            "act now"
        ]

        call_to_action_matches = [
            phrase
            for phrase in call_to_action_phrases
            if phrase in text
        ]

        if len(call_to_action_matches) >= 2:

            detected_characteristics.append(
                "Repeated urgency-oriented call-to-action language"
            )

        # =================================================
        # CHECK 6 - LOW INFORMATION DENSITY
        # =================================================

        word_count = len(
            words
        )

        concrete_information_terms = [
            "location",
            "salary",
            "experience",
            "qualification",
            "skills",
            "responsibilities",
            "working hours",
            "job type",
            "company",
            "address"
        ]

        information_count = sum(
            1
            for term in concrete_information_terms
            if term in text
        )

        if (
            word_count >= 20
            and information_count <= 1
        ):

            detected_characteristics.append(
                "Low concrete-information density"
            )

        # =================================================
        # CHECK 7 - UNUSUAL FORMATTING
        # =================================================

        uppercase_words = [
            word
            for word in job_description.split()
            if word.isalpha() and word.isupper()
        ]

        uppercase_ratio = 0

        if word_count > 0:

            uppercase_ratio = (
                len(uppercase_words)
                / word_count
            )

        if uppercase_ratio > 0.25:

            detected_characteristics.append(
                "High proportion of uppercase text"
            )

        # =================================================
        # DETERMINE CONTENT RISK
        # =================================================

        characteristic_count = len(
            detected_characteristics
        )

        if characteristic_count == 0:

            risk = RISK_LOW

            result["remarks"].append(
                "No significant suspicious content characteristics were detected."
            )

        elif characteristic_count <= 2:

            risk = RISK_MEDIUM

            result["remarks"].append(
                "Some suspicious content characteristics were detected."
            )

        else:

            risk = RISK_HIGH

            result["remarks"].append(
                "Multiple suspicious content characteristics were detected."
            )

        # =================================================
        # FINAL RESPONSE
        # =================================================

        result["status"] = STATUS_SUCCESS
        result["risk"] = risk

        result["data"] = {
            "detected_characteristics": (
                detected_characteristics
            ),
            "characteristic_count": (
                characteristic_count
            ),
            "promotional_matches": (
                promotional_matches
            ),
            "vague_matches": (
                vague_matches
            ),
            "repeated_words": (
                repeated_words
            ),
            "call_to_action_matches": (
                call_to_action_matches
            ),
            "word_count": word_count,
            "information_count": information_count,
            "uppercase_ratio": round(
                uppercase_ratio,
                2
            )
        }

    except Exception as e:

        result["status"] = STATUS_FAILED
        result["risk"] = RISK_HIGH

        result["errors"].append(
            str(e)
        )

    return result